# .github/workflows/deploy-to-server.yml

name: Deploy to Cloud Server

# 触发条件：当 main 分支有新的 push 时
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 步骤一：检出代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 步骤二：部署到服务器
      - name: Deploy to Server via Rsync
        uses: burnett01/rsync-deploy@v7 # 使用专门的 rsync 部署 Action
        with:
          # rsync 的参数，-avzr 表示归档、详细、压缩、递归
          # --delete 表示删除服务器上多余的文件
          switches: -avzr --delete
          # 源目录，'./' 表示仓库的根目录，也就是 runner 上的所有博客文件
          path: ./
          # 远程服务器的目标路径
          remote_path: ${{ secrets.DEPLOY_TARGET }}
          # 远程服务器的地址
          remote_host: ${{ secrets.DEPLOY_HOST }}
          # 远程服务器的用户名
          remote_user: ${{ secrets.DEPLOY_USER }}
          # 远程服务器的自定义端口
          remote_port: ${{ secrets.DEPLOY_PORT }}
          # SSH 私钥
          remote_key: ${{ secrets.DEPLOY_KEY }}
