# deploy-to-server.yml

name: Deploy to Cloud Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 步骤一：检出代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 步骤二：设置 SSH 环境
      # 这个 Action 的作用是把你的私钥加载到 SSH Agent 中，以便后续的 ssh 和 rsync 命令使用
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      # 步骤三：使用 rsync 进行部署
      - name: Deploy with rsync
        run: |
          rsync -avz --delete \
          -e "ssh -p ${{ secrets.DEPLOY_PORT }} -o StrictHostKeyChecking=no" \
          ./ \
          ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_TARGET }}
